# Generated by Django 5.0.7 on 2025-02-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apt_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pyeongNo", models.CharField(max_length=10, verbose_name="평형번호")),
                (
                    "supplyAreaDouble",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="공급면적"
                    ),
                ),
                ("pyeongName", models.CharField(max_length=10, verbose_name="평이름")),
                (
                    "exclusiveArea",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="전용면적"
                    ),
                ),
                (
                    "householdCountByPyeong",
                    models.PositiveIntegerField(verbose_name="세대수"),
                ),
                (
                    "entranceType",
                    models.CharField(max_length=10, verbose_name="계단/복도형"),
                ),
                ("roomCnt", models.CharField(max_length=10, verbose_name="방수")),
                ("bathroomCnt", models.CharField(max_length=10, verbose_name="욕실수")),
                (
                    "complexno_py",
                    models.CharField(
                        default="DEFAULT",
                        max_length=10,
                        unique=True,
                        verbose_name="단지번호_평형",
                    ),
                ),
            ],
            options={
                "verbose_name": "아파트 상세",
                "verbose_name_plural": "아파트 상세 목록",
            },
        ),
        migrations.CreateModel(
            name="Apt_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complexNo",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="단지번호"
                    ),
                ),
                ("complexName", models.CharField(max_length=30, verbose_name="단지명")),
                (
                    "roadAddressPrefix",
                    models.CharField(max_length=20, verbose_name="도로명_1"),
                ),
                (
                    "roadAddress",
                    models.CharField(max_length=20, verbose_name="도로명_2"),
                ),
                ("address", models.CharField(max_length=20, verbose_name="주소_1")),
                (
                    "detailAddress",
                    models.CharField(max_length=20, verbose_name="주소_2"),
                ),
                (
                    "totalDongCount",
                    models.PositiveIntegerField(verbose_name="전체동수"),
                ),
                (
                    "maxSupplyArea",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="최대공급면적"
                    ),
                ),
                (
                    "minSupplyArea",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="최소공급면적"
                    ),
                ),
                (
                    "parkingCountByHousehold",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="세대당주차대수"
                    ),
                ),
                (
                    "parkingPossibleCount",
                    models.PositiveIntegerField(verbose_name="세대수"),
                ),
                (
                    "totalHouseholdCount",
                    models.PositiveIntegerField(verbose_name="세대수"),
                ),
                (
                    "totalLeaseHouseholdCount",
                    models.PositiveIntegerField(verbose_name="임대세대수"),
                ),
                (
                    "useApproveYmd",
                    models.CharField(max_length=30, verbose_name="준공일"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="위도"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="경도"
                    ),
                ),
            ],
            options={
                "verbose_name": "아파트 단지",
                "verbose_name_plural": "아파트 단지 목록",
                "ordering": ["complexName"],
            },
        ),
        migrations.CreateModel(
            name="Apt_photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageKey", models.CharField(max_length=10, verbose_name="단지번호")),
                (
                    "smallCategoryName",
                    models.CharField(max_length=10, null=True, verbose_name="사진설명"),
                ),
                (
                    "imageSrc",
                    models.CharField(max_length=300, verbose_name="이미지_원본"),
                ),
                (
                    "imageId",
                    models.CharField(max_length=100, verbose_name="이미지_아이디"),
                ),
                ("explaination", models.TextField(null=True, verbose_name="사진설명")),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="지역명")),
                (
                    "cortarNo",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="해당지역코드"
                    ),
                ),
            ],
            options={
                "verbose_name": "기준지역",
                "verbose_name_plural": "기준지역 목록",
                "ordering": ["cortarNo"],
            },
        ),
        migrations.CreateModel(
            name="Apt_jeonse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10, verbose_name="거래일")),
                ("price", models.PositiveIntegerField(verbose_name="전세가")),
                (
                    "complexno_py",
                    models.ForeignKey(
                        blank=True,
                        db_column="complexno_py",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apt.apt_detail",
                        to_field="complexno_py",
                        verbose_name="평형 상세",
                    ),
                ),
                (
                    "complexNo",
                    models.ForeignKey(
                        db_column="complexNo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apt.apt_list",
                        to_field="complexNo",
                        verbose_name="단지번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "아파트 전세 상세",
                "verbose_name_plural": "아파트 전세 상세 목록",
            },
        ),
        migrations.AddField(
            model_name="apt_detail",
            name="complexNo",
            field=models.ForeignKey(
                db_column="complexNo",
                on_delete=django.db.models.deletion.CASCADE,
                to="apt.apt_list",
                to_field="complexNo",
                verbose_name="단지번호",
            ),
        ),
        migrations.CreateModel(
            name="Apt_current",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10, verbose_name="기준일")),
                ("price", models.PositiveIntegerField(verbose_name="매매가")),
                ("jeonse", models.PositiveIntegerField(verbose_name="전세가")),
                (
                    "complexno_py",
                    models.ForeignKey(
                        blank=True,
                        db_column="complexno_py",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apt.apt_detail",
                        to_field="complexno_py",
                        verbose_name="평형 상세",
                    ),
                ),
                (
                    "complexNo",
                    models.ForeignKey(
                        db_column="complexNo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apt.apt_list",
                        to_field="complexNo",
                        verbose_name="단지번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "아파트 거래 상세",
                "verbose_name_plural": "아파트 거래 상세 목록",
            },
        ),
        migrations.CreateModel(
            name="Apt_purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10, verbose_name="거래일")),
                ("price", models.PositiveIntegerField(verbose_name="매매가")),
                (
                    "complexNo",
                    models.ForeignKey(
                        db_column="complexNo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apt.apt_list",
                        to_field="complexNo",
                        verbose_name="단지번호",
                    ),
                ),
                (
                    "complexno_py",
                    models.ForeignKey(
                        blank=True,
                        db_column="complexno_py",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apt.apt_detail",
                        to_field="complexno_py",
                        verbose_name="평형 상세",
                    ),
                ),
            ],
            options={
                "verbose_name": "아파트 거래 상세",
                "verbose_name_plural": "아파트 거래 상세 목록",
            },
        ),
        migrations.CreateModel(
            name="Apt_ratio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_price",
                    models.PositiveIntegerField(
                        blank=True, default=0.0, null=True, verbose_name="최고가"
                    ),
                ),
                (
                    "current_price",
                    models.PositiveIntegerField(
                        blank=True, default=0.0, null=True, verbose_name="최근거래가"
                    ),
                ),
                (
                    "current_jeonse",
                    models.PositiveIntegerField(
                        blank=True, default=0.0, null=True, verbose_name="최근전세가"
                    ),
                ),
                (
                    "by_max",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="최고가대비"
                    ),
                ),
                (
                    "by_jeonse",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="전세가대비"
                    ),
                ),
                (
                    "complexNo",
                    models.ForeignKey(
                        blank=True,
                        db_column="complexNo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apt.apt_list",
                        to_field="complexNo",
                        verbose_name="단지번호",
                    ),
                ),
                (
                    "complexno_py",
                    models.ForeignKey(
                        blank=True,
                        db_column="complexno_py",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apt.apt_detail",
                        to_field="complexno_py",
                        verbose_name="평형 상세",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="apt_list",
            name="cortarNo",
            field=models.ForeignKey(
                blank=True,
                db_column="cortarNo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apt.location",
                to_field="cortarNo",
                verbose_name="법정동코드",
            ),
        ),
        migrations.CreateModel(
            name="Apt_jisu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10, verbose_name="거래월")),
                (
                    "jisu",
                    models.FloatField(blank=True, null=True, verbose_name="kb매매지수"),
                ),
                (
                    "jeonse_jisu",
                    models.FloatField(blank=True, null=True, verbose_name="kb전세지수"),
                ),
                (
                    "cortarNo",
                    models.ForeignKey(
                        blank=True,
                        db_column="cortarNo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apt.location",
                        to_field="cortarNo",
                        verbose_name="지역명",
                    ),
                ),
            ],
            options={
                "verbose_name": "아파트 지수",
                "verbose_name_plural": "아파트 지수 목록",
            },
        ),
    ]
