# Generated by Django 5.0.7 on 2025-02-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=20, verbose_name="도시이름")),
                (
                    "city_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="도시코드"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_name",
                    models.CharField(max_length=20, verbose_name="시군구이름"),
                ),
                (
                    "district_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="시군구코드"
                    ),
                ),
                (
                    "city_code",
                    models.ForeignKey(
                        db_column="city_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="region.city",
                        to_field="city_code",
                        verbose_name="도시코드",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neighborhood_name",
                    models.CharField(max_length=20, verbose_name="시군구이름"),
                ),
                (
                    "district_code",
                    models.ForeignKey(
                        db_column="district_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighborhoods",
                        to="region.district",
                        to_field="district_code",
                        verbose_name="시군구코드",
                    ),
                ),
                (
                    "location_code",
                    models.ForeignKey(
                        db_column="neighborhood_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighborhoods",
                        to="apt.location",
                        to_field="cortarNo",
                        verbose_name="읍면동코드",
                    ),
                ),
            ],
        ),
    ]
